Currently Loaded Modulefiles:
  1) gcc/5.3.0        3) xalt/0.7.6       5) python/3.6.3
  2) openmpi/1.10.3   4) PE-gnu/1.0
[or-condo-c57:43382] *** Process received signal ***
[or-condo-c57:43382] Signal: Segmentation fault (11)
[or-condo-c57:43382] Signal code: Address not mapped (1)
[or-condo-c57:43382] Failing at address: 0x3b58890
[or-condo-c57:43382] [ 0] /lib64/libpthread.so.0(+0xf6d0)[0x2b03764c56d0]
[or-condo-c57:43382] [ 1] /lib64/ld-linux-x86-64.so.2(+0x98a0)[0x2b037629b8a0]
[or-condo-c57:43382] [ 2] /lib64/ld-linux-x86-64.so.2(+0xa20f)[0x2b037629c20f]
[or-condo-c57:43382] [ 3] /lib64/ld-linux-x86-64.so.2(+0xef1e)[0x2b03762a0f1e]
[or-condo-c57:43382] [ 4] /lib64/ld-linux-x86-64.so.2(+0x16b2a)[0x2b03762a8b2a]
[or-condo-c57:43382] [ 5] python(_PyGILState_Reinit+0x3d)[0x424a4d]
[or-condo-c57:43382] [ 6] python(PyOS_AfterFork+0x18)[0x43e778]
[or-condo-c57:43382] [ 7] python[0x586026]
[or-condo-c57:43382] [ 8] python(_PyCFunction_FastCallKeywords+0x139)[0x4a92a9]
[or-condo-c57:43382] [ 9] python[0x53fb54]
[or-condo-c57:43382] [10] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43382] [11] python[0x53eb01]
[or-condo-c57:43382] [12] python[0x53fc97]
[or-condo-c57:43382] [13] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43382] [14] python[0x53eb01]
[or-condo-c57:43382] [15] python[0x53fc97]
[or-condo-c57:43382] [16] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43382] [17] python[0x53eb01]
[or-condo-c57:43382] [18] python[0x53fc97]
[or-condo-c57:43382] [19] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43382] [20] python[0x53eb01]
[or-condo-c57:43382] [21] python[0x53fc97]
[or-condo-c57:43382] [22] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43382] [23] python[0x53eb01]
[or-condo-c57:43382] [24] python[0x53fc97]
[or-condo-c57:43382] [25] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43382] [26] python[0x53f771]
[or-condo-c57:43382] [27] python(_PyFunction_FastCallDict+0x156)[0x548946]
[or-condo-c57:43382] [28] python(_PyObject_FastCallDict+0x1ef)[0x4513ef]
[or-condo-c57:43382] [29] python(_PyObject_Call_Prepend+0xcb)[0x4514eb]
[or-condo-c57:43382] *** End of error message ***
[or-condo-c57:43384] *** Process received signal ***
[or-condo-c57:43384] Signal: Segmentation fault (11)
[or-condo-c57:43384] Signal code: Address not mapped (1)
[or-condo-c57:43384] Failing at address: 0x3b58890
[or-condo-c57:43384] [ 0] /lib64/libpthread.so.0(+0xf6d0)[0x2b03764c56d0]
[or-condo-c57:43384] [ 1] /lib64/ld-linux-x86-64.so.2(+0x98a0)[0x2b037629b8a0]
[or-condo-c57:43384] [ 2] /lib64/ld-linux-x86-64.so.2(+0xa20f)[0x2b037629c20f]
[or-condo-c57:43384] [ 3] /lib64/ld-linux-x86-64.so.2(+0xef1e)[0x2b03762a0f1e]
[or-condo-c57:43384] [ 4] /lib64/ld-linux-x86-64.so.2(+0x16b2a)[0x2b03762a8b2a]
[or-condo-c57:43384] [ 5] python(_PyGILState_Reinit+0x3d)[0x424a4d]
[or-condo-c57:43384] [ 6] python(PyOS_AfterFork+0x18)[0x43e778]
[or-condo-c57:43384] [ 7] python[0x586026]
[or-condo-c57:43384] [ 8] python(_PyCFunction_FastCallKeywords+0x139)[0x4a92a9]
[or-condo-c57:43384] [ 9] python[0x53fb54]
[or-condo-c57:43384] [10] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43384] [11] python[0x53eb01]
[or-condo-c57:43384] [12] python[0x53fc97]
[or-condo-c57:43384] [13] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43384] [14] python[0x53eb01]
[or-condo-c57:43384] [15] python[0x53fc97]
[or-condo-c57:43384] [16] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43384] [17] python[0x53eb01]
[or-condo-c57:43384] [18] python(_PyFunction_FastCallDict+0x236)[0x548a26]
[or-condo-c57:43384] [19] python(_PyObject_FastCallDict+0x1ef)[0x4513ef]
[or-condo-c57:43384] [20] python(_PyObject_Call_Prepend+0xcb)[0x4514eb]
[or-condo-c57:43384] [21] python(PyObject_Call+0x60)[0x4510c0]
[or-condo-c57:43384] [22] python[0x4c727b]
[or-condo-c57:43384] [23] python[0x4be9da]
[or-condo-c57:43384] [24] python(_PyObject_FastCallDict+0xa2)[0x4512a2]
[or-condo-c57:43384] [25] python[0x53f8c5]
[or-condo-c57:43384] [26] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43384] [27] python[0x53eb01]
[or-condo-c57:43384] [28] python[0x53fc97]
[or-condo-c57:43384] [29] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43384] *** End of error message ***
/home/29t/.local/lib/python3.6/site-packages/joblib/externals/loky/backend/semaphore_tracker.py:74: UserWarning: semaphore_tracker: process died unexpectedly, relaunching.  Some semaphores might leak.
  warnings.warn('semaphore_tracker: process died unexpectedly, '
[or-condo-c57:43386] *** Process received signal ***
[or-condo-c57:43386] Signal: Segmentation fault (11)
[or-condo-c57:43386] Signal code: Address not mapped (1)
[or-condo-c57:43386] Failing at address: 0x3b58890
[or-condo-c57:43386] [ 0] /lib64/libpthread.so.0(+0xf6d0)[0x2b03764c56d0]
[or-condo-c57:43386] [ 1] /lib64/ld-linux-x86-64.so.2(+0x98a0)[0x2b037629b8a0]
[or-condo-c57:43386] [ 2] /lib64/ld-linux-x86-64.so.2(+0xa20f)[0x2b037629c20f]
[or-condo-c57:43386] [ 3] /lib64/ld-linux-x86-64.so.2(+0xef1e)[0x2b03762a0f1e]
[or-condo-c57:43386] [ 4] /lib64/ld-linux-x86-64.so.2(+0x16b2a)[0x2b03762a8b2a]
[or-condo-c57:43386] [ 5] python(_PyGILState_Reinit+0x3d)[0x424a4d]
[or-condo-c57:43386] [ 6] python(PyOS_AfterFork+0x18)[0x43e778]
[or-condo-c57:43386] [ 7] python[0x586026]
[or-condo-c57:43386] [ 8] python(_PyCFunction_FastCallKeywords+0x139)[0x4a92a9]
[or-condo-c57:43386] [ 9] python[0x53fb54]
[or-condo-c57:43386] [10] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43386] [11] python[0x53eb01]
[or-condo-c57:43386] [12] python[0x53fc97]
[or-condo-c57:43386] [13] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43386] [14] python[0x53eb01]
[or-condo-c57:43386] [15] python[0x53fc97]
[or-condo-c57:43386] [16] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43386] [17] python[0x53eb01]
[or-condo-c57:43386] [18] python[0x53fc97]
[or-condo-c57:43386] [19] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43386] [20] python[0x53eb01]
[or-condo-c57:43386] [21] python[0x53fc97]
[or-condo-c57:43386] [22] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43386] [23] python[0x53eb01]
[or-condo-c57:43386] [24] python[0x53fc97]
[or-condo-c57:43386] [25] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43386] [26] python[0x53f771]
[or-condo-c57:43386] [27] python(_PyFunction_FastCallDict+0x156)[0x548946]
[or-condo-c57:43386] [28] python(_PyObject_FastCallDict+0x1ef)[0x4513ef]
[or-condo-c57:43386] [29] python(_PyObject_Call_Prepend+0xcb)[0x4514eb]
[or-condo-c57:43386] *** End of error message ***
[or-condo-c57:43388] *** Process received signal ***
[or-condo-c57:43388] Signal: Segmentation fault (11)
[or-condo-c57:43388] Signal code: Address not mapped (1)
[or-condo-c57:43388] Failing at address: 0x3b58890
[or-condo-c57:43388] [ 0] /lib64/libpthread.so.0(+0xf6d0)[0x2b03764c56d0]
[or-condo-c57:43388] [ 1] /lib64/ld-linux-x86-64.so.2(+0x98a0)[0x2b037629b8a0]
[or-condo-c57:43388] [ 2] /lib64/ld-linux-x86-64.so.2(+0xa20f)[0x2b037629c20f]
[or-condo-c57:43388] [ 3] /lib64/ld-linux-x86-64.so.2(+0xef1e)[0x2b03762a0f1e]
[or-condo-c57:43388] [ 4] /lib64/ld-linux-x86-64.so.2(+0x16b2a)[0x2b03762a8b2a]
[or-condo-c57:43388] [ 5] python(_PyGILState_Reinit+0x3d)[0x424a4d]
[or-condo-c57:43388] [ 6] python(PyOS_AfterFork+0x18)[0x43e778]
[or-condo-c57:43388] [ 7] python[0x586026]
[or-condo-c57:43388] [ 8] python(_PyCFunction_FastCallKeywords+0x139)[0x4a92a9]
[or-condo-c57:43388] [ 9] python[0x53fb54]
[or-condo-c57:43388] [10] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43388] [11] python[0x53eb01]
[or-condo-c57:43388] [12] python[0x53fc97]
[or-condo-c57:43388] [13] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43388] [14] python[0x53eb01]
[or-condo-c57:43388] [15] python[0x53fc97]
[or-condo-c57:43388] [16] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43388] [17] python[0x53eb01]
[or-condo-c57:43388] [18] python(_PyFunction_FastCallDict+0x236)[0x548a26]
[or-condo-c57:43388] [19] python(_PyObject_FastCallDict+0x1ef)[0x4513ef]
[or-condo-c57:43388] [20] python(_PyObject_Call_Prepend+0xcb)[0x4514eb]
[or-condo-c57:43388] [21] python(PyObject_Call+0x60)[0x4510c0]
[or-condo-c57:43388] [22] python[0x4c727b]
[or-condo-c57:43388] [23] python[0x4be9da]
[or-condo-c57:43388] [24] python(_PyObject_FastCallDict+0xa2)[0x4512a2]
[or-condo-c57:43388] [25] python[0x53f8c5]
[or-condo-c57:43388] [26] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43388] [27] python[0x53eb01]
[or-condo-c57:43388] [28] python[0x53fc97]
[or-condo-c57:43388] [29] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43388] *** End of error message ***
[or-condo-c57:43390] *** Process received signal ***
[or-condo-c57:43390] Signal: Segmentation fault (11)
[or-condo-c57:43390] Signal code: Address not mapped (1)
[or-condo-c57:43390] Failing at address: 0x3b58890
[or-condo-c57:43390] [ 0] /lib64/libpthread.so.0(+0xf6d0)[0x2b03764c56d0]
[or-condo-c57:43390] [ 1] /lib64/ld-linux-x86-64.so.2(+0x98a0)[0x2b037629b8a0]
[or-condo-c57:43390] [ 2] /lib64/ld-linux-x86-64.so.2(+0xa20f)[0x2b037629c20f]
[or-condo-c57:43390] [ 3] /lib64/ld-linux-x86-64.so.2(+0xef1e)[0x2b03762a0f1e]
[or-condo-c57:43390] [ 4] /lib64/ld-linux-x86-64.so.2(+0x16b2a)[0x2b03762a8b2a]
[or-condo-c57:43390] [ 5] python(_PyGILState_Reinit+0x3d)[0x424a4d]
[or-condo-c57:43390] [ 6] python(PyOS_AfterFork+0x18)[0x43e778]
[or-condo-c57:43390] [ 7] python[0x586026]
[or-condo-c57:43390] [ 8] python(_PyCFunction_FastCallKeywords+0x139)[0x4a92a9]
[or-condo-c57:43390] [ 9] python[0x53fb54]
[or-condo-c57:43390] [10] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43390] [11] python[0x53eb01]
[or-condo-c57:43390] [12] python[0x53fc97]
[or-condo-c57:43390] [13] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43390] [14] python[0x53eb01]
[or-condo-c57:43390] [15] python[0x53fc97]
[or-condo-c57:43390] [16] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43390] [17] python[0x53eb01]
[or-condo-c57:43390] [18] python(_PyFunction_FastCallDict+0x236)[0x548a26]
[or-condo-c57:43390] [19] python(_PyObject_FastCallDict+0x1ef)[0x4513ef]
[or-condo-c57:43390] [20] python(_PyObject_Call_Prepend+0xcb)[0x4514eb]
[or-condo-c57:43390] [21] python(PyObject_Call+0x60)[0x4510c0]
[or-condo-c57:43390] [22] python[0x4c727b]
[or-condo-c57:43390] [23] python[0x4be9da]
[or-condo-c57:43390] [24] python(_PyObject_FastCallDict+0xa2)[0x4512a2]
[or-condo-c57:43390] [25] python[0x53f8c5]
[or-condo-c57:43390] [26] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43390] [27] python[0x53eb01]
[or-condo-c57:43390] [28] python[0x53fc97]
[or-condo-c57:43390] [29] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43390] *** End of error message ***
[or-condo-c57:43392] *** Process received signal ***
[or-condo-c57:43392] Signal: Segmentation fault (11)
[or-condo-c57:43392] Signal code: Address not mapped (1)
[or-condo-c57:43392] Failing at address: 0x3b58890
[or-condo-c57:43392] [ 0] /lib64/libpthread.so.0(+0xf6d0)[0x2b03764c56d0]
[or-condo-c57:43392] [ 1] /lib64/ld-linux-x86-64.so.2(+0x98a0)[0x2b037629b8a0]
[or-condo-c57:43392] [ 2] /lib64/ld-linux-x86-64.so.2(+0xa20f)[0x2b037629c20f]
[or-condo-c57:43392] [ 3] /lib64/ld-linux-x86-64.so.2(+0xef1e)[0x2b03762a0f1e]
[or-condo-c57:43392] [ 4] /lib64/ld-linux-x86-64.so.2(+0x16b2a)[0x2b03762a8b2a]
[or-condo-c57:43392] [ 5] python(_PyGILState_Reinit+0x3d)[0x424a4d]
[or-condo-c57:43392] [ 6] python(PyOS_AfterFork+0x18)[0x43e778]
[or-condo-c57:43392] [ 7] python[0x586026]
[or-condo-c57:43392] [ 8] python(_PyCFunction_FastCallKeywords+0x139)[0x4a92a9]
[or-condo-c57:43392] [ 9] python[0x53fb54]
[or-condo-c57:43392] [10] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43392] [11] python[0x53eb01]
[or-condo-c57:43392] [12] python[0x53fc97]
[or-condo-c57:43392] [13] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43392] [14] python[0x53eb01]
[or-condo-c57:43392] [15] python[0x53fc97]
[or-condo-c57:43392] [16] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43392] [17] python[0x53eb01]
[or-condo-c57:43392] [18] python[0x53fc97]
[or-condo-c57:43392] [19] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43392] [20] python[0x53eb01]
[or-condo-c57:43392] [21] python[0x53fc97]
[or-condo-c57:43392] [22] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43392] [23] python[0x53eb01]
[or-condo-c57:43392] [24] python[0x53fc97]
[or-condo-c57:43392] [25] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43392] [26] python[0x53f771]
[or-condo-c57:43392] [27] python(_PyFunction_FastCallDict+0x156)[0x548946]
[or-condo-c57:43392] [28] python(_PyObject_FastCallDict+0x1ef)[0x4513ef]
[or-condo-c57:43392] [29] python(_PyObject_Call_Prepend+0xcb)[0x4514eb]
[or-condo-c57:43392] *** End of error message ***
[or-condo-c57:43394] *** Process received signal ***
[or-condo-c57:43394] Signal: Segmentation fault (11)
[or-condo-c57:43394] Signal code: Address not mapped (1)
[or-condo-c57:43394] Failing at address: 0x3b58890
[or-condo-c57:43394] [ 0] /lib64/libpthread.so.0(+0xf6d0)[0x2b03764c56d0]
[or-condo-c57:43394] [ 1] /lib64/ld-linux-x86-64.so.2(+0x98a0)[0x2b037629b8a0]
[or-condo-c57:43394] [ 2] /lib64/ld-linux-x86-64.so.2(+0xa20f)[0x2b037629c20f]
[or-condo-c57:43394] [ 3] /lib64/ld-linux-x86-64.so.2(+0xef1e)[0x2b03762a0f1e]
[or-condo-c57:43394] [ 4] /lib64/ld-linux-x86-64.so.2(+0x16b2a)[0x2b03762a8b2a]
[or-condo-c57:43394] [ 5] python(_PyGILState_Reinit+0x3d)[0x424a4d]
[or-condo-c57:43394] [ 6] python(PyOS_AfterFork+0x18)[0x43e778]
[or-condo-c57:43394] [ 7] python[0x586026]
[or-condo-c57:43394] [ 8] python(_PyCFunction_FastCallKeywords+0x139)[0x4a92a9]
[or-condo-c57:43394] [ 9] python[0x53fb54]
[or-condo-c57:43394] [10] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43394] [11] python[0x53eb01]
[or-condo-c57:43394] [12] python[0x53fc97]
[or-condo-c57:43394] [13] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43394] [14] python[0x53eb01]
[or-condo-c57:43394] [15] python[0x53fc97]
[or-condo-c57:43394] [16] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43394] [17] python[0x53eb01]
[or-condo-c57:43394] [18] python(_PyFunction_FastCallDict+0x236)[0x548a26]
[or-condo-c57:43394] [19] python(_PyObject_FastCallDict+0x1ef)[0x4513ef]
[or-condo-c57:43394] [20] python(_PyObject_Call_Prepend+0xcb)[0x4514eb]
[or-condo-c57:43394] [21] python(PyObject_Call+0x60)[0x4510c0]
[or-condo-c57:43394] [22] python[0x4c727b]
[or-condo-c57:43394] [23] python[0x4be9da]
[or-condo-c57:43394] [24] python(_PyObject_FastCallDict+0xa2)[0x4512a2]
[or-condo-c57:43394] [25] python[0x53f8c5]
[or-condo-c57:43394] [26] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43394] [27] python[0x53eb01]
[or-condo-c57:43394] [28] python[0x53fc97]
[or-condo-c57:43394] [29] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43394] *** End of error message ***
[or-condo-c57:43396] *** Process received signal ***
[or-condo-c57:43396] Signal: Segmentation fault (11)
[or-condo-c57:43396] Signal code: Address not mapped (1)
[or-condo-c57:43396] Failing at address: 0x3b58890
[or-condo-c57:43396] [ 0] /lib64/libpthread.so.0(+0xf6d0)[0x2b03764c56d0]
[or-condo-c57:43396] [ 1] /lib64/ld-linux-x86-64.so.2(+0x98a0)[0x2b037629b8a0]
[or-condo-c57:43396] [ 2] /lib64/ld-linux-x86-64.so.2(+0xa20f)[0x2b037629c20f]
[or-condo-c57:43396] [ 3] /lib64/ld-linux-x86-64.so.2(+0xef1e)[0x2b03762a0f1e]
[or-condo-c57:43396] [ 4] /lib64/ld-linux-x86-64.so.2(+0x16b2a)[0x2b03762a8b2a]
[or-condo-c57:43396] [ 5] python(_PyGILState_Reinit+0x3d)[0x424a4d]
[or-condo-c57:43396] [ 6] python(PyOS_AfterFork+0x18)[0x43e778]
[or-condo-c57:43396] [ 7] python[0x586026]
[or-condo-c57:43396] [ 8] python(_PyCFunction_FastCallKeywords+0x139)[0x4a92a9]
[or-condo-c57:43396] [ 9] python[0x53fb54]
[or-condo-c57:43396] [10] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43396] [11] python[0x53eb01]
[or-condo-c57:43396] [12] python[0x53fc97]
[or-condo-c57:43396] [13] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43396] [14] python[0x53eb01]
[or-condo-c57:43396] [15] python[0x53fc97]
[or-condo-c57:43396] [16] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43396] [17] python[0x53eb01]
[or-condo-c57:43396] [18] python[0x53fc97]
[or-condo-c57:43396] [19] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43396] [20] python[0x53eb01]
[or-condo-c57:43396] [21] python[0x53fc97]
[or-condo-c57:43396] [22] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43396] [23] python[0x53eb01]
[or-condo-c57:43396] [24] python[0x53fc97]
[or-condo-c57:43396] [25] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43396] [26] python[0x53f771]
[or-condo-c57:43396] [27] python(_PyFunction_FastCallDict+0x156)[0x548946]
[or-condo-c57:43396] [28] python(_PyObject_FastCallDict+0x1ef)[0x4513ef]
[or-condo-c57:43396] [29] python(_PyObject_Call_Prepend+0xcb)[0x4514eb]
[or-condo-c57:43396] *** End of error message ***
[or-condo-c57:43398] *** Process received signal ***
[or-condo-c57:43398] Signal: Segmentation fault (11)
[or-condo-c57:43398] Signal code: Address not mapped (1)
[or-condo-c57:43398] Failing at address: 0x3b58890
[or-condo-c57:43398] [ 0] /lib64/libpthread.so.0(+0xf6d0)[0x2b03764c56d0]
[or-condo-c57:43398] [ 1] /lib64/ld-linux-x86-64.so.2(+0x98a0)[0x2b037629b8a0]
[or-condo-c57:43398] [ 2] /lib64/ld-linux-x86-64.so.2(+0xa20f)[0x2b037629c20f]
[or-condo-c57:43398] [ 3] /lib64/ld-linux-x86-64.so.2(+0xef1e)[0x2b03762a0f1e]
[or-condo-c57:43398] [ 4] /lib64/ld-linux-x86-64.so.2(+0x16b2a)[0x2b03762a8b2a]
[or-condo-c57:43398] [ 5] python(_PyGILState_Reinit+0x3d)[0x424a4d]
[or-condo-c57:43398] [ 6] python(PyOS_AfterFork+0x18)[0x43e778]
[or-condo-c57:43398] [ 7] python[0x586026]
[or-condo-c57:43398] [ 8] python(_PyCFunction_FastCallKeywords+0x139)[0x4a92a9]
[or-condo-c57:43398] [ 9] python[0x53fb54]
[or-condo-c57:43398] [10] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43398] [11] python[0x53eb01]
[or-condo-c57:43398] [12] python[0x53fc97]
[or-condo-c57:43398] [13] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43398] [14] python[0x53eb01]
[or-condo-c57:43398] [15] python[0x53fc97]
[or-condo-c57:43398] [16] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43398] [17] python[0x53eb01]
[or-condo-c57:43398] [18] python(_PyFunction_FastCallDict+0x236)[0x548a26]
[or-condo-c57:43398] [19] python(_PyObject_FastCallDict+0x1ef)[0x4513ef]
[or-condo-c57:43398] [20] python(_PyObject_Call_Prepend+0xcb)[0x4514eb]
[or-condo-c57:43398] [21] python(PyObject_Call+0x60)[0x4510c0]
[or-condo-c57:43398] [22] python[0x4c727b]
[or-condo-c57:43398] [23] python[0x4be9da]
[or-condo-c57:43398] [24] python(_PyObject_FastCallDict+0xa2)[0x4512a2]
[or-condo-c57:43398] [25] python[0x53f8c5]
[or-condo-c57:43398] [26] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43398] [27] python[0x53eb01]
[or-condo-c57:43398] [28] python[0x53fc97]
[or-condo-c57:43398] [29] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43398] *** End of error message ***
[or-condo-c57:43400] *** Process received signal ***
[or-condo-c57:43400] Signal: Segmentation fault (11)
[or-condo-c57:43400] Signal code: Address not mapped (1)
[or-condo-c57:43400] Failing at address: 0x3b58890
[or-condo-c57:43400] [ 0] /lib64/libpthread.so.0(+0xf6d0)[0x2b03764c56d0]
[or-condo-c57:43400] [ 1] /lib64/ld-linux-x86-64.so.2(+0x98a0)[0x2b037629b8a0]
[or-condo-c57:43400] [ 2] /lib64/ld-linux-x86-64.so.2(+0xa20f)[0x2b037629c20f]
[or-condo-c57:43400] [ 3] /lib64/ld-linux-x86-64.so.2(+0xef1e)[0x2b03762a0f1e]
[or-condo-c57:43400] [ 4] /lib64/ld-linux-x86-64.so.2(+0x16b2a)[0x2b03762a8b2a]
[or-condo-c57:43400] [ 5] python(_PyGILState_Reinit+0x3d)[0x424a4d]
[or-condo-c57:43400] [ 6] python(PyOS_AfterFork+0x18)[0x43e778]
[or-condo-c57:43400] [ 7] python[0x586026]
[or-condo-c57:43400] [ 8] python(_PyCFunction_FastCallKeywords+0x139)[0x4a92a9]
[or-condo-c57:43400] [ 9] python[0x53fb54]
[or-condo-c57:43400] [10] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43400] [11] python[0x53eb01]
[or-condo-c57:43400] [12] python[0x53fc97]
[or-condo-c57:43400] [13] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43400] [14] python[0x53eb01]
[or-condo-c57:43400] [15] python[0x53fc97]
[or-condo-c57:43400] [16] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43400] [17] python[0x53eb01]
[or-condo-c57:43400] [18] python[0x53fc97]
[or-condo-c57:43400] [19] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43400] [20] python[0x53eb01]
[or-condo-c57:43400] [21] python[0x53fc97]
[or-condo-c57:43400] [22] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43400] [23] python[0x53eb01]
[or-condo-c57:43400] [24] python[0x53fc97]
[or-condo-c57:43400] [25] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43400] [26] python[0x53f771]
[or-condo-c57:43400] [27] python(_PyFunction_FastCallDict+0x156)[0x548946]
[or-condo-c57:43400] [28] python(_PyObject_FastCallDict+0x1ef)[0x4513ef]
[or-condo-c57:43400] [29] python(_PyObject_Call_Prepend+0xcb)[0x4514eb]
[or-condo-c57:43400] *** End of error message ***
[or-condo-c57:43402] *** Process received signal ***
[or-condo-c57:43402] Signal: Segmentation fault (11)
[or-condo-c57:43402] Signal code: Address not mapped (1)
[or-condo-c57:43402] Failing at address: 0x3b58890
[or-condo-c57:43402] [ 0] /lib64/libpthread.so.0(+0xf6d0)[0x2b03764c56d0]
[or-condo-c57:43402] [ 1] /lib64/ld-linux-x86-64.so.2(+0x98a0)[0x2b037629b8a0]
[or-condo-c57:43402] [ 2] /lib64/ld-linux-x86-64.so.2(+0xa20f)[0x2b037629c20f]
[or-condo-c57:43402] [ 3] /lib64/ld-linux-x86-64.so.2(+0xef1e)[0x2b03762a0f1e]
[or-condo-c57:43402] [ 4] /lib64/ld-linux-x86-64.so.2(+0x16b2a)[0x2b03762a8b2a]
[or-condo-c57:43402] [ 5] python(_PyGILState_Reinit+0x3d)[0x424a4d]
[or-condo-c57:43402] [ 6] python(PyOS_AfterFork+0x18)[0x43e778]
[or-condo-c57:43402] [ 7] python[0x586026]
[or-condo-c57:43402] [ 8] python(_PyCFunction_FastCallKeywords+0x139)[0x4a92a9]
[or-condo-c57:43402] [ 9] python[0x53fb54]
[or-condo-c57:43402] [10] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43402] [11] python[0x53eb01]
[or-condo-c57:43402] [12] python[0x53fc97]
[or-condo-c57:43402] [13] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43402] [14] python[0x53eb01]
[or-condo-c57:43402] [15] python[0x53fc97]
[or-condo-c57:43402] [16] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43402] [17] python[0x53eb01]
[or-condo-c57:43402] [18] python(_PyFunction_FastCallDict+0x236)[0x548a26]
[or-condo-c57:43402] [19] python(_PyObject_FastCallDict+0x1ef)[0x4513ef]
[or-condo-c57:43402] [20] python(_PyObject_Call_Prepend+0xcb)[0x4514eb]
[or-condo-c57:43402] [21] python(PyObject_Call+0x60)[0x4510c0]
[or-condo-c57:43402] [22] python[0x4c727b]
[or-condo-c57:43402] [23] python[0x4be9da]
[or-condo-c57:43402] [24] python(_PyObject_FastCallDict+0xa2)[0x4512a2]
[or-condo-c57:43402] [25] python[0x53f8c5]
[or-condo-c57:43402] [26] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43402] [27] python[0x53eb01]
[or-condo-c57:43402] [28] python[0x53fc97]
[or-condo-c57:43402] [29] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43402] *** End of error message ***
[or-condo-c57:43404] *** Process received signal ***
[or-condo-c57:43404] Signal: Segmentation fault (11)
[or-condo-c57:43404] Signal code: Address not mapped (1)
[or-condo-c57:43404] Failing at address: 0x3b58890
[or-condo-c57:43404] [ 0] /lib64/libpthread.so.0(+0xf6d0)[0x2b03764c56d0]
[or-condo-c57:43404] [ 1] /lib64/ld-linux-x86-64.so.2(+0x98a0)[0x2b037629b8a0]
[or-condo-c57:43404] [ 2] /lib64/ld-linux-x86-64.so.2(+0xa20f)[0x2b037629c20f]
[or-condo-c57:43404] [ 3] /lib64/ld-linux-x86-64.so.2(+0xef1e)[0x2b03762a0f1e]
[or-condo-c57:43404] [ 4] /lib64/ld-linux-x86-64.so.2(+0x16b2a)[0x2b03762a8b2a]
[or-condo-c57:43404] [ 5] python(_PyGILState_Reinit+0x3d)[0x424a4d]
[or-condo-c57:43404] [ 6] python(PyOS_AfterFork+0x18)[0x43e778]
[or-condo-c57:43404] [ 7] python[0x586026]
[or-condo-c57:43404] [ 8] python(_PyCFunction_FastCallKeywords+0x139)[0x4a92a9]
[or-condo-c57:43404] [ 9] python[0x53fb54]
[or-condo-c57:43404] [10] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43404] [11] python[0x53eb01]
[or-condo-c57:43404] [12] python[0x53fc97]
[or-condo-c57:43404] [13] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43404] [14] python[0x53eb01]
[or-condo-c57:43404] [15] python[0x53fc97]
[or-condo-c57:43404] [16] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43404] [17] python[0x53eb01]
[or-condo-c57:43404] [18] python[0x53fc97]
[or-condo-c57:43404] [19] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43404] [20] python[0x53eb01]
[or-condo-c57:43404] [21] python[0x53fc97]
[or-condo-c57:43404] [22] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43404] [23] python[0x53eb01]
[or-condo-c57:43404] [24] python[0x53fc97]
[or-condo-c57:43404] [25] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43404] [26] python[0x53f771]
[or-condo-c57:43404] [27] python(_PyFunction_FastCallDict+0x156)[0x548946]
[or-condo-c57:43404] [28] python(_PyObject_FastCallDict+0x1ef)[0x4513ef]
[or-condo-c57:43404] [29] python(_PyObject_Call_Prepend+0xcb)[0x4514eb]
[or-condo-c57:43404] *** End of error message ***
[or-condo-c57:43406] *** Process received signal ***
[or-condo-c57:43406] Signal: Segmentation fault (11)
[or-condo-c57:43406] Signal code: Address not mapped (1)
[or-condo-c57:43406] Failing at address: 0x3b58890
[or-condo-c57:43406] [ 0] /lib64/libpthread.so.0(+0xf6d0)[0x2b03764c56d0]
[or-condo-c57:43406] [ 1] /lib64/ld-linux-x86-64.so.2(+0x98a0)[0x2b037629b8a0]
[or-condo-c57:43406] [ 2] /lib64/ld-linux-x86-64.so.2(+0xa20f)[0x2b037629c20f]
[or-condo-c57:43406] [ 3] /lib64/ld-linux-x86-64.so.2(+0xef1e)[0x2b03762a0f1e]
[or-condo-c57:43406] [ 4] /lib64/ld-linux-x86-64.so.2(+0x16b2a)[0x2b03762a8b2a]
[or-condo-c57:43406] [ 5] python(_PyGILState_Reinit+0x3d)[0x424a4d]
[or-condo-c57:43406] [ 6] python(PyOS_AfterFork+0x18)[0x43e778]
[or-condo-c57:43406] [ 7] python[0x586026]
[or-condo-c57:43406] [ 8] python(_PyCFunction_FastCallKeywords+0x139)[0x4a92a9]
[or-condo-c57:43406] [ 9] python[0x53fb54]
[or-condo-c57:43406] [10] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43406] [11] python[0x53eb01]
[or-condo-c57:43406] [12] python[0x53fc97]
[or-condo-c57:43406] [13] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43406] [14] python[0x53eb01]
[or-condo-c57:43406] [15] python[0x53fc97]
[or-condo-c57:43406] [16] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43406] [17] python[0x53eb01]
[or-condo-c57:43406] [18] python(_PyFunction_FastCallDict+0x236)[0x548a26]
[or-condo-c57:43406] [19] python(_PyObject_FastCallDict+0x1ef)[0x4513ef]
[or-condo-c57:43406] [20] python(_PyObject_Call_Prepend+0xcb)[0x4514eb]
[or-condo-c57:43406] [21] python(PyObject_Call+0x60)[0x4510c0]
[or-condo-c57:43406] [22] python[0x4c727b]
[or-condo-c57:43406] [23] python[0x4be9da]
[or-condo-c57:43406] [24] python(_PyObject_FastCallDict+0xa2)[0x4512a2]
[or-condo-c57:43406] [25] python[0x53f8c5]
[or-condo-c57:43406] [26] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43406] [27] python[0x53eb01]
[or-condo-c57:43406] [28] python[0x53fc97]
[or-condo-c57:43406] [29] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43406] *** End of error message ***
[or-condo-c57:43408] *** Process received signal ***
[or-condo-c57:43408] Signal: Segmentation fault (11)
[or-condo-c57:43408] Signal code: Address not mapped (1)
[or-condo-c57:43408] Failing at address: 0x3b58890
[or-condo-c57:43408] [ 0] /lib64/libpthread.so.0(+0xf6d0)[0x2b03764c56d0]
[or-condo-c57:43408] [ 1] /lib64/ld-linux-x86-64.so.2(+0x98a0)[0x2b037629b8a0]
[or-condo-c57:43408] [ 2] /lib64/ld-linux-x86-64.so.2(+0xa20f)[0x2b037629c20f]
[or-condo-c57:43408] [ 3] /lib64/ld-linux-x86-64.so.2(+0xef1e)[0x2b03762a0f1e]
[or-condo-c57:43408] [ 4] /lib64/ld-linux-x86-64.so.2(+0x16b2a)[0x2b03762a8b2a]
[or-condo-c57:43408] [ 5] python(_PyGILState_Reinit+0x3d)[0x424a4d]
[or-condo-c57:43408] [ 6] python(PyOS_AfterFork+0x18)[0x43e778]
[or-condo-c57:43408] [ 7] python[0x586026]
[or-condo-c57:43408] [ 8] python(_PyCFunction_FastCallKeywords+0x139)[0x4a92a9]
[or-condo-c57:43408] [ 9] python[0x53fb54]
[or-condo-c57:43408] [10] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43408] [11] python[0x53eb01]
[or-condo-c57:43408] [12] python[0x53fc97]
[or-condo-c57:43408] [13] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43408] [14] python[0x53eb01]
[or-condo-c57:43408] [15] python[0x53fc97]
[or-condo-c57:43408] [16] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43408] [17] python[0x53eb01]
[or-condo-c57:43408] [18] python[0x53fc97]
[or-condo-c57:43408] [19] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43408] [20] python[0x53eb01]
[or-condo-c57:43408] [21] python[0x53fc97]
[or-condo-c57:43408] [22] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43408] [23] python[0x53eb01]
[or-condo-c57:43408] [24] python[0x53fc97]
[or-condo-c57:43408] [25] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43408] [26] python[0x53f771]
[or-condo-c57:43408] [27] python(_PyFunction_FastCallDict+0x156)[0x548946]
[or-condo-c57:43408] [28] python(_PyObject_FastCallDict+0x1ef)[0x4513ef]
[or-condo-c57:43408] [29] python(_PyObject_Call_Prepend+0xcb)[0x4514eb]
[or-condo-c57:43408] *** End of error message ***
[or-condo-c57:43410] *** Process received signal ***
[or-condo-c57:43410] Signal: Segmentation fault (11)
[or-condo-c57:43410] Signal code: Address not mapped (1)
[or-condo-c57:43410] Failing at address: 0x3b58890
[or-condo-c57:43410] [ 0] /lib64/libpthread.so.0(+0xf6d0)[0x2b03764c56d0]
[or-condo-c57:43410] [ 1] /lib64/ld-linux-x86-64.so.2(+0x98a0)[0x2b037629b8a0]
[or-condo-c57:43410] [ 2] /lib64/ld-linux-x86-64.so.2(+0xa20f)[0x2b037629c20f]
[or-condo-c57:43410] [ 3] /lib64/ld-linux-x86-64.so.2(+0xef1e)[0x2b03762a0f1e]
[or-condo-c57:43410] [ 4] /lib64/ld-linux-x86-64.so.2(+0x16b2a)[0x2b03762a8b2a]
[or-condo-c57:43410] [ 5] python(_PyGILState_Reinit+0x3d)[0x424a4d]
[or-condo-c57:43410] [ 6] python(PyOS_AfterFork+0x18)[0x43e778]
[or-condo-c57:43410] [ 7] python[0x586026]
[or-condo-c57:43410] [ 8] python(_PyCFunction_FastCallKeywords+0x139)[0x4a92a9]
[or-condo-c57:43410] [ 9] python[0x53fb54]
[or-condo-c57:43410] [10] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43410] [11] python[0x53eb01]
[or-condo-c57:43410] [12] python[0x53fc97]
[or-condo-c57:43410] [13] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43410] [14] python[0x53eb01]
[or-condo-c57:43410] [15] python[0x53fc97]
[or-condo-c57:43410] [16] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43410] [17] python[0x53eb01]
[or-condo-c57:43410] [18] python(_PyFunction_FastCallDict+0x236)[0x548a26]
[or-condo-c57:43410] [19] python(_PyObject_FastCallDict+0x1ef)[0x4513ef]
[or-condo-c57:43410] [20] python(_PyObject_Call_Prepend+0xcb)[0x4514eb]
[or-condo-c57:43410] [21] python(PyObject_Call+0x60)[0x4510c0]
[or-condo-c57:43410] [22] python[0x4c727b]
[or-condo-c57:43410] [23] python[0x4be9da]
[or-condo-c57:43410] [24] python(_PyObject_FastCallDict+0xa2)[0x4512a2]
[or-condo-c57:43410] [25] python[0x53f8c5]
[or-condo-c57:43410] [26] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43410] [27] python[0x53eb01]
[or-condo-c57:43410] [28] python[0x53fc97]
[or-condo-c57:43410] [29] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43410] *** End of error message ***
[or-condo-c57:43412] *** Process received signal ***
[or-condo-c57:43412] Signal: Segmentation fault (11)
[or-condo-c57:43412] Signal code: Address not mapped (1)
[or-condo-c57:43412] Failing at address: 0x3b58890
[or-condo-c57:43412] [ 0] /lib64/libpthread.so.0(+0xf6d0)[0x2b03764c56d0]
[or-condo-c57:43412] [ 1] /lib64/ld-linux-x86-64.so.2(+0x98a0)[0x2b037629b8a0]
[or-condo-c57:43412] [ 2] /lib64/ld-linux-x86-64.so.2(+0xa20f)[0x2b037629c20f]
[or-condo-c57:43412] [ 3] /lib64/ld-linux-x86-64.so.2(+0xef1e)[0x2b03762a0f1e]
[or-condo-c57:43412] [ 4] /lib64/ld-linux-x86-64.so.2(+0x16b2a)[0x2b03762a8b2a]
[or-condo-c57:43412] [ 5] python(_PyGILState_Reinit+0x3d)[0x424a4d]
[or-condo-c57:43412] [ 6] python(PyOS_AfterFork+0x18)[0x43e778]
[or-condo-c57:43412] [ 7] python[0x586026]
[or-condo-c57:43412] [ 8] python(_PyCFunction_FastCallKeywords+0x139)[0x4a92a9]
[or-condo-c57:43412] [ 9] python[0x53fb54]
[or-condo-c57:43412] [10] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43412] [11] python[0x53eb01]
[or-condo-c57:43412] [12] python[0x53fc97]
[or-condo-c57:43412] [13] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43412] [14] python[0x53eb01]
[or-condo-c57:43412] [15] python[0x53fc97]
[or-condo-c57:43412] [16] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43412] [17] python[0x53eb01]
[or-condo-c57:43412] [18] python[0x53fc97]
[or-condo-c57:43412] [19] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43412] [20] python[0x53eb01]
[or-condo-c57:43412] [21] python[0x53fc97]
[or-condo-c57:43412] [22] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43412] [23] python[0x53eb01]
[or-condo-c57:43412] [24] python[0x53fc97]
[or-condo-c57:43412] [25] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43412] [26] python[0x53f771]
[or-condo-c57:43412] [27] python(_PyFunction_FastCallDict+0x156)[0x548946]
[or-condo-c57:43412] [28] python(_PyObject_FastCallDict+0x1ef)[0x4513ef]
[or-condo-c57:43412] [29] python(_PyObject_Call_Prepend+0xcb)[0x4514eb]
[or-condo-c57:43412] *** End of error message ***
[or-condo-c57:43414] *** Process received signal ***
[or-condo-c57:43414] Signal: Segmentation fault (11)
[or-condo-c57:43414] Signal code: Address not mapped (1)
[or-condo-c57:43414] Failing at address: 0x3b58890
[or-condo-c57:43414] [ 0] /lib64/libpthread.so.0(+0xf6d0)[0x2b03764c56d0]
[or-condo-c57:43414] [ 1] /lib64/ld-linux-x86-64.so.2(+0x98a0)[0x2b037629b8a0]
[or-condo-c57:43414] [ 2] /lib64/ld-linux-x86-64.so.2(+0xa20f)[0x2b037629c20f]
[or-condo-c57:43414] [ 3] /lib64/ld-linux-x86-64.so.2(+0xef1e)[0x2b03762a0f1e]
[or-condo-c57:43414] [ 4] /lib64/ld-linux-x86-64.so.2(+0x16b2a)[0x2b03762a8b2a]
[or-condo-c57:43414] [ 5] python(_PyGILState_Reinit+0x3d)[0x424a4d]
[or-condo-c57:43414] [ 6] python(PyOS_AfterFork+0x18)[0x43e778]
[or-condo-c57:43414] [ 7] python[0x586026]
[or-condo-c57:43414] [ 8] python(_PyCFunction_FastCallKeywords+0x139)[0x4a92a9]
[or-condo-c57:43414] [ 9] python[0x53fb54]
[or-condo-c57:43414] [10] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43414] [11] python[0x53eb01]
[or-condo-c57:43414] [12] python[0x53fc97]
[or-condo-c57:43414] [13] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43414] [14] python[0x53eb01]
[or-condo-c57:43414] [15] python[0x53fc97]
[or-condo-c57:43414] [16] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43414] [17] python[0x53eb01]
[or-condo-c57:43414] [18] python(_PyFunction_FastCallDict+0x236)[0x548a26]
[or-condo-c57:43414] [19] python(_PyObject_FastCallDict+0x1ef)[0x4513ef]
[or-condo-c57:43414] [20] python(_PyObject_Call_Prepend+0xcb)[0x4514eb]
[or-condo-c57:43414] [21] python(PyObject_Call+0x60)[0x4510c0]
[or-condo-c57:43414] [22] python[0x4c727b]
[or-condo-c57:43414] [23] python[0x4be9da]
[or-condo-c57:43414] [24] python(_PyObject_FastCallDict+0xa2)[0x4512a2]
[or-condo-c57:43414] [25] python[0x53f8c5]
[or-condo-c57:43414] [26] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43414] [27] python[0x53eb01]
[or-condo-c57:43414] [28] python[0x53fc97]
[or-condo-c57:43414] [29] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43414] *** End of error message ***
[or-condo-c57:43416] *** Process received signal ***
[or-condo-c57:43416] Signal: Segmentation fault (11)
[or-condo-c57:43416] Signal code: Address not mapped (1)
[or-condo-c57:43416] Failing at address: 0x3b58890
[or-condo-c57:43416] [ 0] /lib64/libpthread.so.0(+0xf6d0)[0x2b03764c56d0]
[or-condo-c57:43416] [ 1] /lib64/ld-linux-x86-64.so.2(+0x98a0)[0x2b037629b8a0]
[or-condo-c57:43416] [ 2] /lib64/ld-linux-x86-64.so.2(+0xa20f)[0x2b037629c20f]
[or-condo-c57:43416] [ 3] /lib64/ld-linux-x86-64.so.2(+0xef1e)[0x2b03762a0f1e]
[or-condo-c57:43416] [ 4] /lib64/ld-linux-x86-64.so.2(+0x16b2a)[0x2b03762a8b2a]
[or-condo-c57:43416] [ 5] python(_PyGILState_Reinit+0x3d)[0x424a4d]
[or-condo-c57:43416] [ 6] python(PyOS_AfterFork+0x18)[0x43e778]
[or-condo-c57:43416] [ 7] python[0x586026]
[or-condo-c57:43416] [ 8] python(_PyCFunction_FastCallKeywords+0x139)[0x4a92a9]
[or-condo-c57:43416] [ 9] python[0x53fb54]
[or-condo-c57:43416] [10] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43416] [11] python[0x53eb01]
[or-condo-c57:43416] [12] python[0x53fc97]
[or-condo-c57:43416] [13] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43416] [14] python[0x53eb01]
[or-condo-c57:43416] [15] python[0x53fc97]
[or-condo-c57:43416] [16] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43416] [17] python[0x53eb01]
[or-condo-c57:43416] [18] python[0x53fc97]
[or-condo-c57:43416] [19] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43416] [20] python[0x53eb01]
[or-condo-c57:43416] [21] python[0x53fc97]
[or-condo-c57:43416] [22] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43416] [23] python[0x53eb01]
[or-condo-c57:43416] [24] python[0x53fc97]
[or-condo-c57:43416] [25] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43416] [26] python[0x53f771]
[or-condo-c57:43416] [27] python(_PyFunction_FastCallDict+0x156)[0x548946]
[or-condo-c57:43416] [28] python(_PyObject_FastCallDict+0x1ef)[0x4513ef]
[or-condo-c57:43416] [29] python(_PyObject_Call_Prepend+0xcb)[0x4514eb]
[or-condo-c57:43416] *** End of error message ***
[or-condo-c57:43418] *** Process received signal ***
[or-condo-c57:43418] Signal: Segmentation fault (11)
[or-condo-c57:43418] Signal code: Address not mapped (1)
[or-condo-c57:43418] Failing at address: 0x3b58890
[or-condo-c57:43418] [ 0] /lib64/libpthread.so.0(+0xf6d0)[0x2b03764c56d0]
[or-condo-c57:43418] [ 1] /lib64/ld-linux-x86-64.so.2(+0x98a0)[0x2b037629b8a0]
[or-condo-c57:43418] [ 2] /lib64/ld-linux-x86-64.so.2(+0xa20f)[0x2b037629c20f]
[or-condo-c57:43418] [ 3] /lib64/ld-linux-x86-64.so.2(+0xef1e)[0x2b03762a0f1e]
[or-condo-c57:43418] [ 4] /lib64/ld-linux-x86-64.so.2(+0x16b2a)[0x2b03762a8b2a]
[or-condo-c57:43418] [ 5] python(_PyGILState_Reinit+0x3d)[0x424a4d]
[or-condo-c57:43418] [ 6] python(PyOS_AfterFork+0x18)[0x43e778]
[or-condo-c57:43418] [ 7] python[0x586026]
[or-condo-c57:43418] [ 8] python(_PyCFunction_FastCallKeywords+0x139)[0x4a92a9]
[or-condo-c57:43418] [ 9] python[0x53fb54]
[or-condo-c57:43418] [10] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43418] [11] python[0x53eb01]
[or-condo-c57:43418] [12] python[0x53fc97]
[or-condo-c57:43418] [13] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43418] [14] python[0x53eb01]
[or-condo-c57:43418] [15] python[0x53fc97]
[or-condo-c57:43418] [16] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43418] [17] python[0x53eb01]
[or-condo-c57:43418] [18] python(_PyFunction_FastCallDict+0x236)[0x548a26]
[or-condo-c57:43418] [19] python(_PyObject_FastCallDict+0x1ef)[0x4513ef]
[or-condo-c57:43418] [20] python(_PyObject_Call_Prepend+0xcb)[0x4514eb]
[or-condo-c57:43418] [21] python(PyObject_Call+0x60)[0x4510c0]
[or-condo-c57:43418] [22] python[0x4c727b]
[or-condo-c57:43418] [23] python[0x4be9da]
[or-condo-c57:43418] [24] python(_PyObject_FastCallDict+0xa2)[0x4512a2]
[or-condo-c57:43418] [25] python[0x53f8c5]
[or-condo-c57:43418] [26] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43418] [27] python[0x53eb01]
[or-condo-c57:43418] [28] python[0x53fc97]
[or-condo-c57:43418] [29] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43418] *** End of error message ***
[or-condo-c57:43420] *** Process received signal ***
[or-condo-c57:43420] Signal: Segmentation fault (11)
[or-condo-c57:43420] Signal code: Address not mapped (1)
[or-condo-c57:43420] Failing at address: 0x3b58890
[or-condo-c57:43420] [ 0] /lib64/libpthread.so.0(+0xf6d0)[0x2b03764c56d0]
[or-condo-c57:43420] [ 1] /lib64/ld-linux-x86-64.so.2(+0x98a0)[0x2b037629b8a0]
[or-condo-c57:43420] [ 2] /lib64/ld-linux-x86-64.so.2(+0xa20f)[0x2b037629c20f]
[or-condo-c57:43420] [ 3] /lib64/ld-linux-x86-64.so.2(+0xef1e)[0x2b03762a0f1e]
[or-condo-c57:43420] [ 4] /lib64/ld-linux-x86-64.so.2(+0x16b2a)[0x2b03762a8b2a]
[or-condo-c57:43420] [ 5] python(_PyGILState_Reinit+0x3d)[0x424a4d]
[or-condo-c57:43420] [ 6] python(PyOS_AfterFork+0x18)[0x43e778]
[or-condo-c57:43420] [ 7] python[0x586026]
[or-condo-c57:43420] [ 8] python(_PyCFunction_FastCallKeywords+0x139)[0x4a92a9]
[or-condo-c57:43420] [ 9] python[0x53fb54]
[or-condo-c57:43420] [10] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43420] [11] python[0x53eb01]
[or-condo-c57:43420] [12] python[0x53fc97]
[or-condo-c57:43420] [13] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43420] [14] python[0x53eb01]
[or-condo-c57:43420] [15] python[0x53fc97]
[or-condo-c57:43420] [16] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43420] [17] python[0x53eb01]
[or-condo-c57:43420] [18] python[0x53fc97]
[or-condo-c57:43420] [19] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43420] [20] python[0x53eb01]
[or-condo-c57:43420] [21] python[0x53fc97]
[or-condo-c57:43420] [22] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43420] [23] python[0x53eb01]
[or-condo-c57:43420] [24] python[0x53fc97]
[or-condo-c57:43420] [25] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43420] [26] python[0x53f771]
[or-condo-c57:43420] [27] python(_PyFunction_FastCallDict+0x156)[0x548946]
[or-condo-c57:43420] [28] python(_PyObject_FastCallDict+0x1ef)[0x4513ef]
[or-condo-c57:43420] [29] python(_PyObject_Call_Prepend+0xcb)[0x4514eb]
[or-condo-c57:43420] *** End of error message ***
[or-condo-c57:43422] *** Process received signal ***
[or-condo-c57:43422] Signal: Segmentation fault (11)
[or-condo-c57:43422] Signal code: Address not mapped (1)
[or-condo-c57:43422] Failing at address: 0x3b58890
[or-condo-c57:43422] [ 0] /lib64/libpthread.so.0(+0xf6d0)[0x2b03764c56d0]
[or-condo-c57:43422] [ 1] /lib64/ld-linux-x86-64.so.2(+0x98a0)[0x2b037629b8a0]
[or-condo-c57:43422] [ 2] /lib64/ld-linux-x86-64.so.2(+0xa20f)[0x2b037629c20f]
[or-condo-c57:43422] [ 3] /lib64/ld-linux-x86-64.so.2(+0xef1e)[0x2b03762a0f1e]
[or-condo-c57:43422] [ 4] /lib64/ld-linux-x86-64.so.2(+0x16b2a)[0x2b03762a8b2a]
[or-condo-c57:43422] [ 5] python(_PyGILState_Reinit+0x3d)[0x424a4d]
[or-condo-c57:43422] [ 6] python(PyOS_AfterFork+0x18)[0x43e778]
[or-condo-c57:43422] [ 7] python[0x586026]
[or-condo-c57:43422] [ 8] python(_PyCFunction_FastCallKeywords+0x139)[0x4a92a9]
[or-condo-c57:43422] [ 9] python[0x53fb54]
[or-condo-c57:43422] [10] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43422] [11] python[0x53eb01]
[or-condo-c57:43422] [12] python[0x53fc97]
[or-condo-c57:43422] [13] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43422] [14] python[0x53eb01]
[or-condo-c57:43422] [15] python[0x53fc97]
[or-condo-c57:43422] [16] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43422] [17] python[0x53eb01]
[or-condo-c57:43422] [18] python(_PyFunction_FastCallDict+0x236)[0x548a26]
[or-condo-c57:43422] [19] python(_PyObject_FastCallDict+0x1ef)[0x4513ef]
[or-condo-c57:43422] [20] python(_PyObject_Call_Prepend+0xcb)[0x4514eb]
[or-condo-c57:43422] [21] python(PyObject_Call+0x60)[0x4510c0]
[or-condo-c57:43422] [22] python[0x4c727b]
[or-condo-c57:43422] [23] python[0x4be9da]
[or-condo-c57:43422] [24] python(_PyObject_FastCallDict+0xa2)[0x4512a2]
[or-condo-c57:43422] [25] python[0x53f8c5]
[or-condo-c57:43422] [26] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43422] [27] python[0x53eb01]
[or-condo-c57:43422] [28] python[0x53fc97]
[or-condo-c57:43422] [29] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43422] *** End of error message ***
[or-condo-c57:43424] *** Process received signal ***
[or-condo-c57:43424] Signal: Segmentation fault (11)
[or-condo-c57:43424] Signal code: Address not mapped (1)
[or-condo-c57:43424] Failing at address: 0x3b58890
[or-condo-c57:43424] [ 0] /lib64/libpthread.so.0(+0xf6d0)[0x2b03764c56d0]
[or-condo-c57:43424] [ 1] /lib64/ld-linux-x86-64.so.2(+0x98a0)[0x2b037629b8a0]
[or-condo-c57:43424] [ 2] /lib64/ld-linux-x86-64.so.2(+0xa20f)[0x2b037629c20f]
[or-condo-c57:43424] [ 3] /lib64/ld-linux-x86-64.so.2(+0xef1e)[0x2b03762a0f1e]
[or-condo-c57:43424] [ 4] /lib64/ld-linux-x86-64.so.2(+0x16b2a)[0x2b03762a8b2a]
[or-condo-c57:43424] [ 5] python(_PyGILState_Reinit+0x3d)[0x424a4d]
[or-condo-c57:43424] [ 6] python(PyOS_AfterFork+0x18)[0x43e778]
[or-condo-c57:43424] [ 7] python[0x586026]
[or-condo-c57:43424] [ 8] python(_PyCFunction_FastCallKeywords+0x139)[0x4a92a9]
[or-condo-c57:43424] [ 9] python[0x53fb54]
[or-condo-c57:43424] [10] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43424] [11] python[0x53eb01]
[or-condo-c57:43424] [12] python[0x53fc97]
[or-condo-c57:43424] [13] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43424] [14] python[0x53eb01]
[or-condo-c57:43424] [15] python[0x53fc97]
[or-condo-c57:43424] [16] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43424] [17] python[0x53eb01]
[or-condo-c57:43424] [18] python[0x53fc97]
[or-condo-c57:43424] [19] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43424] [20] python[0x53eb01]
[or-condo-c57:43424] [21] python[0x53fc97]
[or-condo-c57:43424] [22] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43424] [23] python[0x53eb01]
[or-condo-c57:43424] [24] python[0x53fc97]
[or-condo-c57:43424] [25] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43424] [26] python[0x53f771]
[or-condo-c57:43424] [27] python(_PyFunction_FastCallDict+0x156)[0x548946]
[or-condo-c57:43424] [28] python(_PyObject_FastCallDict+0x1ef)[0x4513ef]
[or-condo-c57:43424] [29] python(_PyObject_Call_Prepend+0xcb)[0x4514eb]
[or-condo-c57:43424] *** End of error message ***
[or-condo-c57:43426] *** Process received signal ***
[or-condo-c57:43426] Signal: Segmentation fault (11)
[or-condo-c57:43426] Signal code: Address not mapped (1)
[or-condo-c57:43426] Failing at address: 0x3b58890
[or-condo-c57:43426] [ 0] /lib64/libpthread.so.0(+0xf6d0)[0x2b03764c56d0]
[or-condo-c57:43426] [ 1] /lib64/ld-linux-x86-64.so.2(+0x98a0)[0x2b037629b8a0]
[or-condo-c57:43426] [ 2] /lib64/ld-linux-x86-64.so.2(+0xa20f)[0x2b037629c20f]
[or-condo-c57:43426] [ 3] /lib64/ld-linux-x86-64.so.2(+0xef1e)[0x2b03762a0f1e]
[or-condo-c57:43426] [ 4] /lib64/ld-linux-x86-64.so.2(+0x16b2a)[0x2b03762a8b2a]
[or-condo-c57:43426] [ 5] python(_PyGILState_Reinit+0x3d)[0x424a4d]
[or-condo-c57:43426] [ 6] python(PyOS_AfterFork+0x18)[0x43e778]
[or-condo-c57:43426] [ 7] python[0x586026]
[or-condo-c57:43426] [ 8] python(_PyCFunction_FastCallKeywords+0x139)[0x4a92a9]
[or-condo-c57:43426] [ 9] python[0x53fb54]
[or-condo-c57:43426] [10] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43426] [11] python[0x53eb01]
[or-condo-c57:43426] [12] python[0x53fc97]
[or-condo-c57:43426] [13] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43426] [14] python[0x53eb01]
[or-condo-c57:43426] [15] python[0x53fc97]
[or-condo-c57:43426] [16] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43426] [17] python[0x53eb01]
[or-condo-c57:43426] [18] python(_PyFunction_FastCallDict+0x236)[0x548a26]
[or-condo-c57:43426] [19] python(_PyObject_FastCallDict+0x1ef)[0x4513ef]
[or-condo-c57:43426] [20] python(_PyObject_Call_Prepend+0xcb)[0x4514eb]
[or-condo-c57:43426] [21] python(PyObject_Call+0x60)[0x4510c0]
[or-condo-c57:43426] [22] python[0x4c727b]
[or-condo-c57:43426] [23] python[0x4be9da]
[or-condo-c57:43426] [24] python(_PyObject_FastCallDict+0xa2)[0x4512a2]
[or-condo-c57:43426] [25] python[0x53f8c5]
[or-condo-c57:43426] [26] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43426] [27] python[0x53eb01]
[or-condo-c57:43426] [28] python[0x53fc97]
[or-condo-c57:43426] [29] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43426] *** End of error message ***
exception calling callback for <Future at 0x2b03f3fa9b00 state=finished raised TerminatedWorkerError>
Traceback (most recent call last):
  File "/home/29t/.local/lib/python3.6/site-packages/joblib/externals/loky/_base.py", line 625, in _invoke_callbacks
    callback(self)
  File "/home/29t/.local/lib/python3.6/site-packages/joblib/parallel.py", line 309, in __call__
    self.parallel.dispatch_next()
  File "/home/29t/.local/lib/python3.6/site-packages/joblib/parallel.py", line 731, in dispatch_next
    if not self.dispatch_one_batch(self._original_iterator):
  File "/home/29t/.local/lib/python3.6/site-packages/joblib/parallel.py", line 759, in dispatch_one_batch
    self._dispatch(tasks)
  File "/home/29t/.local/lib/python3.6/site-packages/joblib/parallel.py", line 716, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/home/29t/.local/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 510, in apply_async
    future = self._workers.submit(SafeFunction(func))
  File "/home/29t/.local/lib/python3.6/site-packages/joblib/externals/loky/reusable_executor.py", line 151, in submit
    fn, *args, **kwargs)
  File "/home/29t/.local/lib/python3.6/site-packages/joblib/externals/loky/process_executor.py", line 1022, in submit
    raise self._flags.broken
joblib.externals.loky.process_executor.TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker. The exit codes of the workers are {SIGSEGV(-11), SIGSEGV(-11), SIGSEGV(-11), SIGSEGV(-11), SIGSEGV(-11), SIGSEGV(-11), SIGSEGV(-11), SIGSEGV(-11), SIGSEGV(-11), SIGSEGV(-11), SIGSEGV(-11), SIGSEGV(-11)}
[or-condo-c57:43430] *** Process received signal ***
[or-condo-c57:43430] Signal: Segmentation fault (11)
[or-condo-c57:43430] Signal code: Address not mapped (1)
[or-condo-c57:43430] Failing at address: 0x3b58890
[or-condo-c57:43430] [ 0] /lib64/libpthread.so.0(+0xf6d0)[0x2b03764c56d0]
[or-condo-c57:43430] [ 1] /lib64/ld-linux-x86-64.so.2(+0x98a0)[0x2b037629b8a0]
[or-condo-c57:43430] [ 2] /lib64/ld-linux-x86-64.so.2(+0xa20f)[0x2b037629c20f]
[or-condo-c57:43430] [ 3] /lib64/ld-linux-x86-64.so.2(+0xef1e)[0x2b03762a0f1e]
[or-condo-c57:43430] [ 4] /lib64/ld-linux-x86-64.so.2(+0x16b2a)[0x2b03762a8b2a]
[or-condo-c57:43430] [ 5] python(_PyGILState_Reinit+0x3d)[0x424a4d]
[or-condo-c57:43430] [ 6] python(PyOS_AfterFork+0x18)[0x43e778]
[or-condo-c57:43430] [ 7] python[0x586026]
[or-condo-c57:43430] [ 8] python(_PyCFunction_FastCallKeywords+0x139)[0x4a92a9]
[or-condo-c57:43430] [ 9] python[0x53fb54]
[or-condo-c57:43430] [10] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43430] [11] python[0x53eb01]
[or-condo-c57:43430] [12] python[0x53fc97]
[or-condo-c57:43430] [13] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43430] [14] python[0x53eb01]
[or-condo-c57:43430] [15] python[0x53fc97]
[or-condo-c57:43430] [16] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43430] [17] python[0x53eb01]
[or-condo-c57:43430] [18] python[0x53fc97]
[or-condo-c57:43430] [19] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43430] [20] python[0x53eb01]
[or-condo-c57:43430] [21] python[0x53fc97]
[or-condo-c57:43430] [22] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43430] [23] python[0x53f771]
[or-condo-c57:43430] [24] python(PyEval_EvalCodeEx+0x6d)[0x54066d]
[or-condo-c57:43430] [25] python[0x481227]
[or-condo-c57:43430] [26] python(PyObject_Call+0x60)[0x4510c0]
[or-condo-c57:43430] [27] python(_PyEval_EvalFrameDefault+0x4262)[0x544da2]
[or-condo-c57:43430] [28] python[0x53f771]
[or-condo-c57:43430] [29] python(_PyFunction_FastCallDict+0x156)[0x548946]
[or-condo-c57:43430] *** End of error message ***
[or-condo-c57:43432] *** Process received signal ***
[or-condo-c57:43432] Signal: Segmentation fault (11)
[or-condo-c57:43432] Signal code: Address not mapped (1)
[or-condo-c57:43432] Failing at address: 0x3b58890
[or-condo-c57:43432] [ 0] /lib64/libpthread.so.0(+0xf6d0)[0x2b03764c56d0]
[or-condo-c57:43432] [ 1] /lib64/ld-linux-x86-64.so.2(+0x98a0)[0x2b037629b8a0]
[or-condo-c57:43432] [ 2] /lib64/ld-linux-x86-64.so.2(+0xa20f)[0x2b037629c20f]
[or-condo-c57:43432] [ 3] /lib64/ld-linux-x86-64.so.2(+0xef1e)[0x2b03762a0f1e]
[or-condo-c57:43432] [ 4] /lib64/ld-linux-x86-64.so.2(+0x16b2a)[0x2b03762a8b2a]
[or-condo-c57:43432] [ 5] python(_PyGILState_Reinit+0x3d)[0x424a4d]
[or-condo-c57:43432] [ 6] python(PyOS_AfterFork+0x18)[0x43e778]
[or-condo-c57:43432] [ 7] python[0x586026]
[or-condo-c57:43432] [ 8] python(_PyCFunction_FastCallKeywords+0x139)[0x4a92a9]
[or-condo-c57:43432] [ 9] python[0x53fb54]
[or-condo-c57:43432] [10] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43432] [11] python[0x53eb01]
[or-condo-c57:43432] [12] python[0x53fc97]
[or-condo-c57:43432] [13] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43432] [14] python[0x53eb01]
[or-condo-c57:43432] [15] Traceback (most recent call last):
  File "bay_inf_script_500subset.py", line 63, in <module>
    h5_bayes_group = abi_subset.compute()
  File "/home/29t/.local/lib/python3.6/site-packages/pyUSID/processing/process.py", line 657, in compute
    self._unit_computation(*args, **kwargs)
  File "/lustre/or-hydra/cades-birthright/29t/pycroscopy/pycroscopy/analysis/bayesian_inference/parallelTiming/bayesian_inference.py", line 293, in _unit_computation
    shifted_i_meas = parallel_compute(self.data[:, ::self.parse_mod], get_shifted_response, cores=self._cores, func_args=[self.shift_index])
  File "/home/29t/.local/lib/python3.6/site-packages/pyUSID/processing/comp_utils.py", line 155, in parallel_compute
    results = joblib.Parallel(n_jobs=cores)(values)
  File "/home/29t/.local/lib/python3.6/site-packages/joblib/parallel.py", line 934, in __call__
    self.retrieve()
  File "/home/29t/.local/lib/python3.6/site-packages/joblib/parallel.py", line 833, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/29t/.local/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 521, in wrap_future_result
    return future.result(timeout=timeout)
  File "/software/dev_tools/swtree/cs400_centos7.2_pe2016-08/python/3.6.3/centos7.2_gnu5.3.0/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/software/dev_tools/swtree/cs400_centos7.2_pe2016-08/python/3.6.3/centos7.2_gnu5.3.0/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/29t/.local/lib/python3.6/site-packages/joblib/externals/loky/_base.py", line 625, in _invoke_callbacks
    callback(self)
  File "/home/29t/.local/lib/python3.6/site-packages/joblib/parallel.py", line 309, in __call__
    self.parallel.dispatch_next()
  File "/home/29t/.local/lib/python3.6/site-packages/joblib/parallel.py", line 731, in dispatch_next
    if not self.dispatch_one_batch(self._original_iterator):
  File "/home/29t/.local/lib/python3.6/site-packages/joblib/parallel.py", line 759, in dispatch_one_batch
    self._dispatch(tasks)
  File "/home/29t/.local/lib/python3.6/site-packages/joblib/parallel.py", line 716, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/home/29t/.local/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 510, in apply_async
    future = self._workers.submit(SafeFunction(func))
  File "/home/29t/.local/lib/python3.6/site-packages/joblib/externals/loky/reusable_executor.py", line 151, in submit
    fn, *args, **kwargs)
  File "/home/29t/.local/lib/python3.6/site-packages/joblib/externals/loky/process_executor.py", line 1022, in submit
    raise self._flags.broken
joblib.externals.loky.process_executor.TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker. The exit codes of the workers are {SIGSEGV(-11), SIGSEGV(-11), SIGSEGV(-11), SIGSEGV(-11), SIGSEGV(-11), SIGSEGV(-11), SIGSEGV(-11), SIGSEGV(-11), SIGSEGV(-11), SIGSEGV(-11), SIGSEGV(-11), SIGSEGV(-11)}
python[0x53fc97]
[or-condo-c57:43432] [16] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43432] [17] python[0x53eb01]
[or-condo-c57:43432] [18] python[0x53fc97]
[or-condo-c57:43432] [19] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43432] [20] python[0x53eb01]
[or-condo-c57:43432] [21] python[0x53fc97]
[or-condo-c57:43432] [22] python(_PyEval_EvalFrameDefault+0x3e6c)[0x5449ac]
[or-condo-c57:43432] [23] python[0x53f771]
[or-condo-c57:43432] [24] python(PyEval_EvalCodeEx+0x6d)[0x54066d]
[or-condo-c57:43432] [25] python[0x481227]
[or-condo-c57:43432] [26] python(PyObject_Call+0x60)[0x4510c0]
[or-condo-c57:43432] [27] python(_PyEval_EvalFrameDefault+0x4262)[0x544da2]
[or-condo-c57:43432] [28] python[0x53f771]
[or-condo-c57:43432] [29] python(_PyFunction_FastCallDict+0x156)[0x548946]
[or-condo-c57:43432] *** End of error message ***
